development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: timemanagement
  pool: 5
  password: jiten123

test: &TEST
  adapter: postgresql
  encoding: SQL_ASCII
  database: timemanagement
  pool: 5
  password: jiten123

production:
  adapter: postgresql
  encoding: SQL_ASCII
  database: timemanagement
  pool: 5
  password: jiten123

cucumber:
  <<: *TEST